### ISSUE TITLE
unreliable debugging and reset

### ISSUE THREAD

**Issue by heechul** [platformio/platform-sifive#1]
Hello, 

I'm using a HiFive1 revb board and the VSCode + PlatformIO combination on Ubuntu 18.04.  

I can successfully program and run my code on the board using the vscode+platformio, but found its debugging is unreliable. 

I am able to debug my code sometimes, but most of the time, It doesn't work. When it doesn't work, the following is the log message from the debug console and the red led is blinking at this point. 

```
Loading section .text, size 0x776 lma 0x20010168
Loading section .rodata, size 0x8a0 lma 0x200108e0
Loading section .init_array, size 0xc lma 0x20011180
Loading section .data, size 0xfc lma 0x2001118c
Start address 0x20010000, load size 4742
Writing register (pc = 0x20010000)
Transfer rate: 18 KB/sec, 948 bytes/write.
Received monitor command: halt
Halting target CPU...
...Target halted (PC = 0x20010000)
Received monitor command: reset
Resetting target
Resetting target
PlatformIO: Initialization completed
PlatformIO: Resume the execution to `debug_init_break = tbreak main`
PlatformIO: More configuration options -> http://bit.ly/pio-debug
Starting target CPU...
```

And the following is my platformio.ini file. (I tried 'platformio-sifive.git' as well, but made no difference). 

```
[env:hifive1-revb]
platform = sifive
; platform = https://github.com/platformio/platform-sifive.git
board = hifive1-revb
framework = freedom-e-sdk
monitor_port = /dev/ttyACM0
monitor_speed = 115200
```

I haven't experienced this kind of debugging issues when using FreedomStudio (but I would much prefer to use platformio+vscode).

Thanks!

**Comment by valeros** [comment]
Hi @heechul ! Could you please describe what exactly doesn't work? Does it reach the first breakpoint at main function?

**Comment by heechul** [comment]
No. it doesn't. It stuck at "Starting target CPU..."

**Comment by heechul** [comment]
@valeros I tried windows and it seems that debugging works fine there. Were you able to reproduce the problem on ubuntu?

**Comment by valeros** [comment]
@heechul Sorry, don't have this board at hand at the moment, but looks like the problem might be related to the JLink GDB server. Would be great if you could try to debug board using JLink tool from FreedomStudio. It should look something like this:
```
[env:hifive1-revb]
platform = sifive
; platform = https://github.com/platformio/platform-sifive.git
board = hifive1-revb
framework = freedom-e-sdk
monitor_port = /dev/ttyACM0
monitor_speed = 115200
debug_tool = custom
debug_server =
    /path/to/FreedomStduio/SiFive/jlink/JLinkGDBServer
    -singlerun
    -if
    JTAG
    -select
    USB
    -speed
    1000
    -jtagconf
    -1,-1 
    -port
    2331
    -device
    FE310

```

**Comment by heechul** [comment]
Ok. it seems to work (sort of). 
I still get stuck at "Starting target CPU..." but if I re-try once more, it always seems to work after the change.

**Comment by heechul** [comment]
Actually, it seems the same was the case even before the change: i.e., when stuck at "Starting target ...", I click stop button in the debug ribbon, and retry to debug, then it seems to work regardless which gdbserver is being used.

**Comment by heechul** [comment]
@valeros I think I previously shared incorrect information regarding the behaviors on windows and ubuntu. Over the week, I have tested two windows 10 and two ubuntu 18.04 computers. My finding so far is that debugging doesn't work reliably on both windows and ubuntu settings. Sometimes it does work, but I couldn't find a way to make it work reliably using PlatformIO.  

On the other hand, I have not yet encountered any problems on debugging when using FreedomStudio, on both windows and ubuntu machines. 

So, I think the debugging issues I have with PlatformIO are neither caused by JLINK driver, nor the operating system differences. 

Were you able to access to the board?

**Comment by ivankravets** [comment]
We've just updated J-Link GDB server to 6.50a. Could you re-run `pio update` command and try debugging again? It should be more reliable.

**Comment by ivankravets** [comment]
Should be fixed in https://github.com/platformio/platformio-core/commit/2c242944c7021112db9ad974c96df3e42454d216

Please re-run `pio upgrade --dev` too. So:
```
pio upgrade --dev
pio update
```

it should work now.

**Comment by heechul** [comment]
@ivankravets It does seems to solve the problem. Thank you very much!
