### ISSUE TITLE
problem installing tool-openocd-riscv

### ISSUE THREAD

**Issue by yon264** [platformio/platform-sifive#2]
Working on VSCode on the freedom-e300-hifive1 board.
I tried to upload my project to the board, and got an error when installing the tool-openocd-riscv that said: 
"Error: Could not find a version that satisfies the requirement '~2.1000.20181218' for your system 'windows_x86'"
However, I am working on windows x64 OS.
Then I tried to copy the folder from https://bintray.com/platformio/dl-packages/tool-openocd-riscv#files into C:\\Users\User\.platformio\packages manually, still got the same error.

**Comment by ivankravets** [comment]
Yes, we have only openOCD for Windows x64. Could you try a version for x64 https://bintray.com/platformio/dl-packages/tool-openocd-riscv/2.1000.20190501#files ? Does it work?

**Comment by ivankravets** [comment]
Could you uninstall exiting Python and install x64 version? I see that it detects your system as x86. It's strange. Thanks!

**Comment by ivankravets** [comment]
Please reopen if you still need help
